print("how old are you ?", end=' ')
age = input()
print("how tall are you ?",end=' ')
height = input()
print("how much do you weigh",end= ' ')
weight = input()
print(f"So you are {age} year old and your height is {height} and your weight is {weight} kg")